version: "4.29"
services:
  postgres:
   container_name: postgres
   image: postgres:latest
   environment:
    POSTGRES_DB: "db" 
    POSTGRES_USER: "postgres" 
    POSTRGRESS_PASSWORD: "123"
   volumes:
    - postrges-data:/var/lib/postgresql/data
   ports:
    - "5432:5432"


volumes:
 postgres_data: